package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Cancha generated by hbm2java
 */
public class Cancha  implements java.io.Serializable {


     private Long codigocancha;
     private String diametro;
     private String direccion;
     private Set<Partido> partidos = new HashSet<Partido>(0);

    public Cancha() {
    }

	
    public Cancha(Long codigocancha, String diametro, String direccion) {
        this.codigocancha = codigocancha;
        this.diametro = diametro;
        this.direccion = direccion;
    }
    public Cancha(Long codigocancha, String diametro, String direccion, Set<Partido> partidos) {
       this.codigocancha = codigocancha;
       this.diametro = diametro;
       this.direccion = direccion;
       this.partidos = partidos;
    }
   
    public Long getCodigocancha() {
        return this.codigocancha;
    }
    
    public void setCodigocancha(Long codigocancha) {
        this.codigocancha = codigocancha;
    }
    public String getDiametro() {
        return this.diametro;
    }
    
    public void setDiametro(String diametro) {
        this.diametro = diametro;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }




}


