package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {

//Empleado
     private Long codigoempleado;
     private Tipoempleado tipoempleado;
     private String nombre;
     private String apellido;
     private Long email;
     private Long password;
     private Set<Partido> partidos = new HashSet<Partido>(0);
     private Set<Torneo> torneos = new HashSet<Torneo>(0);

    public Empleado() {
    }

	
    public Empleado(Long codigoempleado, String nombre, String apellido, Long email, Long password) {
        this.codigoempleado = codigoempleado;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
    }
    public Empleado(Long codigoempleado, Tipoempleado tipoempleado, String nombre, String apellido, Long email, Long password, Set<Partido> partidos, Set<Torneo> torneos) {
       this.codigoempleado = codigoempleado;
       this.tipoempleado = tipoempleado;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.password = password;
       this.partidos = partidos;
       this.torneos = torneos;
    }
   
    public Long getCodigoempleado() {
        return this.codigoempleado;
    }
    
    public void setCodigoempleado(Long codigoempleado) {
        this.codigoempleado = codigoempleado;
    }
    public Tipoempleado getTipoempleado() {
        return this.tipoempleado;
    }
    
    public void setTipoempleado(Tipoempleado tipoempleado) {
        this.tipoempleado = tipoempleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Long getEmail() {
        return this.email;
    }
    
    public void setEmail(Long email) {
        this.email = email;
    }
    public Long getPassword() {
        return this.password;
    }
    
    public void setPassword(Long password) {
        this.password = password;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }
    public Set<Torneo> getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Set<Torneo> torneos) {
        this.torneos = torneos;
    }




}


