package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private Long codigojugador;
     private Pais pais;
     private String nombre;
     private Integer ranking;
     private String activo;
     private Set<PartidoJugador> partidoJugadors = new HashSet<PartidoJugador>(0);
     private Set<Equipo> equipos = new HashSet<Equipo>(0);

    public Jugador() {
    }

	
    public Jugador(Long codigojugador, String nombre, Integer ranking, String activo) {
        this.codigojugador = codigojugador;
        this.nombre = nombre;
        this.ranking = ranking;
        this.activo = activo;
    }
    public Jugador(Long codigojugador, Pais pais, String nombre, Integer ranking, String activo, Set<PartidoJugador> partidoJugadors, Set<Equipo> equipos) {
       this.codigojugador = codigojugador;
       this.pais = pais;
       this.nombre = nombre;
       this.ranking = ranking;
       this.activo = activo;
       this.partidoJugadors = partidoJugadors;
       this.equipos = equipos;
    }
   
    public Long getCodigojugador() {
        return this.codigojugador;
    }
    
    public void setCodigojugador(Long codigojugador) {
        this.codigojugador = codigojugador;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getRanking() {
        return this.ranking;
    }
    
    public void setRanking(Integer ranking) {
        this.ranking = ranking;
    }
    public String getActivo() {
        return this.activo;
    }
    
    public void setActivo(String activo) {
        this.activo = activo;
    }
    public Set<PartidoJugador> getPartidoJugadors() {
        return this.partidoJugadors;
    }
    
    public void setPartidoJugadors(Set<PartidoJugador> partidoJugadors) {
        this.partidoJugadors = partidoJugadors;
    }
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }




}


