package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final



/**
 * PartidoUsuario generated by hbm2java
 */
public class PartidoUsuario  implements java.io.Serializable {


     private Long codigopartidoUsuario;
     private Partido partido;
     private Usuario usuario;

    public PartidoUsuario() {
    }

	
    public PartidoUsuario(Long codigopartidoUsuario) {
        this.codigopartidoUsuario = codigopartidoUsuario;
    }
    public PartidoUsuario(Long codigopartidoUsuario, Partido partido, Usuario usuario) {
       this.codigopartidoUsuario = codigopartidoUsuario;
       this.partido = partido;
       this.usuario = usuario;
    }
   
    public Long getCodigopartidoUsuario() {
        return this.codigopartidoUsuario;
    }
    
    public void setCodigopartidoUsuario(Long codigopartidoUsuario) {
        this.codigopartidoUsuario = codigopartidoUsuario;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


