package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private Long codigopartido;
     private Cancha cancha;
     private Empleado empleado;
     private Ronda ronda;
     private String ganador;
     private Date fecha;
     private Set<PartidoUsuario> partidoUsuarios = new HashSet<PartidoUsuario>(0);
     private Set<PartidoResultado> partidoResultados = new HashSet<PartidoResultado>(0);
     private Set<PartidoJugador> partidoJugadors = new HashSet<PartidoJugador>(0);

    public Partido() {
    }

	
    public Partido(Long codigopartido, String ganador, Date fecha) {
        this.codigopartido = codigopartido;
        this.ganador = ganador;
        this.fecha = fecha;
    }
    public Partido(Long codigopartido, Cancha cancha, Empleado empleado, Ronda ronda, String ganador, Date fecha, Set<PartidoUsuario> partidoUsuarios, Set<PartidoResultado> partidoResultados, Set<PartidoJugador> partidoJugadors) {
       this.codigopartido = codigopartido;
       this.cancha = cancha;
       this.empleado = empleado;
       this.ronda = ronda;
       this.ganador = ganador;
       this.fecha = fecha;
       this.partidoUsuarios = partidoUsuarios;
       this.partidoResultados = partidoResultados;
       this.partidoJugadors = partidoJugadors;
    }
   
    public Long getCodigopartido() {
        return this.codigopartido;
    }
    
    public void setCodigopartido(Long codigopartido) {
        this.codigopartido = codigopartido;
    }
    public Cancha getCancha() {
        return this.cancha;
    }
    
    public void setCancha(Cancha cancha) {
        this.cancha = cancha;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Ronda getRonda() {
        return this.ronda;
    }
    
    public void setRonda(Ronda ronda) {
        this.ronda = ronda;
    }
    public String getGanador() {
        return this.ganador;
    }
    
    public void setGanador(String ganador) {
        this.ganador = ganador;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<PartidoUsuario> getPartidoUsuarios() {
        return this.partidoUsuarios;
    }
    
    public void setPartidoUsuarios(Set<PartidoUsuario> partidoUsuarios) {
        this.partidoUsuarios = partidoUsuarios;
    }
    public Set<PartidoResultado> getPartidoResultados() {
        return this.partidoResultados;
    }
    
    public void setPartidoResultados(Set<PartidoResultado> partidoResultados) {
        this.partidoResultados = partidoResultados;
    }
    public Set<PartidoJugador> getPartidoJugadors() {
        return this.partidoJugadors;
    }
    
    public void setPartidoJugadors(Set<PartidoJugador> partidoJugadors) {
        this.partidoJugadors = partidoJugadors;
    }




}


