package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final



/**
 * PartidoResultado generated by hbm2java
 */
public class PartidoResultado  implements java.io.Serializable {


     private Long codigopatridoResultado;
     private Partido partido;
     private Resultado resultado;

    public PartidoResultado() {
    }

	
    public PartidoResultado(Long codigopatridoResultado) {
        this.codigopatridoResultado = codigopatridoResultado;
    }
    public PartidoResultado(Long codigopatridoResultado, Partido partido, Resultado resultado) {
       this.codigopatridoResultado = codigopatridoResultado;
       this.partido = partido;
       this.resultado = resultado;
    }
   
    public Long getCodigopatridoResultado() {
        return this.codigopatridoResultado;
    }
    
    public void setCodigopatridoResultado(Long codigopatridoResultado) {
        this.codigopatridoResultado = codigopatridoResultado;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public Resultado getResultado() {
        return this.resultado;
    }
    
    public void setResultado(Resultado resultado) {
        this.resultado = resultado;
    }




}


