package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Ronda generated by hbm2java
 */
public class Ronda  implements java.io.Serializable {


     private Long codigoronda;
     private Torneo torneo;
     private String nombre;
     private Double precio;
     private Integer puntos;
     private Set<Partido> partidos = new HashSet<Partido>(0);

    public Ronda() {
    }

	
    public Ronda(Long codigoronda, String nombre, Double precio) {
        this.codigoronda = codigoronda;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Ronda(Long codigoronda, Torneo torneo, String nombre, Double precio, Integer puntos, Set<Partido> partidos) {
       this.codigoronda = codigoronda;
       this.torneo = torneo;
       this.nombre = nombre;
       this.precio = precio;
       this.puntos = puntos;
       this.partidos = partidos;
    }
   
    public Long getCodigoronda() {
        return this.codigoronda;
    }
    
    public void setCodigoronda(Long codigoronda) {
        this.codigoronda = codigoronda;
    }
    public Torneo getTorneo() {
        return this.torneo;
    }
    
    public void setTorneo(Torneo torneo) {
        this.torneo = torneo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Set<Partido> getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set<Partido> partidos) {
        this.partidos = partidos;
    }




}


