package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoempleado generated by hbm2java
 */
public class Tipoempleado  implements java.io.Serializable {


     private Long codigotipoempleado;
     private String descripcion;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Tipoempleado() {
    }

	
    public Tipoempleado(Long codigotipoempleado, String descripcion) {
        this.codigotipoempleado = codigotipoempleado;
        this.descripcion = descripcion;
    }
    public Tipoempleado(Long codigotipoempleado, String descripcion, Set<Empleado> empleados) {
       this.codigotipoempleado = codigotipoempleado;
       this.descripcion = descripcion;
       this.empleados = empleados;
    }
   
    public Long getCodigotipoempleado() {
        return this.codigotipoempleado;
    }
    
    public void setCodigotipoempleado(Long codigotipoempleado) {
        this.codigotipoempleado = codigotipoempleado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


