package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Torneo generated by hbm2java
 */
public class Torneo  implements java.io.Serializable {


     private Long codigotorneo;
     private Empleado empleado;
     private Tipotorneo tipotorneo;
     private Date fechainicio;
     private Date fechafin;
     private Set<Ronda> rondas = new HashSet<Ronda>(0);

    public Torneo() {
    }

	
    public Torneo(Long codigotorneo, Empleado empleado, Tipotorneo tipotorneo, Date fechainicio, Date fechafin) {
        this.codigotorneo = codigotorneo;
        this.empleado = empleado;
        this.tipotorneo = tipotorneo;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
    }
    public Torneo(Long codigotorneo, Empleado empleado, Tipotorneo tipotorneo, Date fechainicio, Date fechafin, Set<Ronda> rondas) {
       this.codigotorneo = codigotorneo;
       this.empleado = empleado;
       this.tipotorneo = tipotorneo;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.rondas = rondas;
    }
   
    public Long getCodigotorneo() {
        return this.codigotorneo;
    }
    
    public void setCodigotorneo(Long codigotorneo) {
        this.codigotorneo = codigotorneo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Tipotorneo getTipotorneo() {
        return this.tipotorneo;
    }
    
    public void setTipotorneo(Tipotorneo tipotorneo) {
        this.tipotorneo = tipotorneo;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Set<Ronda> getRondas() {
        return this.rondas;
    }
    
    public void setRondas(Set<Ronda> rondas) {
        this.rondas = rondas;
    }




}


