package co.edu.usbcali.modelo;
// Generated 14/11/2016 04:39:29 PM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Long codigousuario;
     private String nombre;
     private String apellido;
     private String email;
     private String password;
     private Set<PartidoUsuario> partidoUsuarios = new HashSet<PartidoUsuario>(0);

    public Usuario() {
    }

	
    public Usuario(Long codigousuario, String nombre, String apellido, String email, String password) {
        this.codigousuario = codigousuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.email = email;
        this.password = password;
    }
    public Usuario(Long codigousuario, String nombre, String apellido, String email, String password, Set<PartidoUsuario> partidoUsuarios) {
       this.codigousuario = codigousuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.email = email;
       this.password = password;
       this.partidoUsuarios = partidoUsuarios;
    }
   
    public Long getCodigousuario() {
        return this.codigousuario;
    }
    
    public void setCodigousuario(Long codigousuario) {
        this.codigousuario = codigousuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set<PartidoUsuario> getPartidoUsuarios() {
        return this.partidoUsuarios;
    }
    
    public void setPartidoUsuarios(Set<PartidoUsuario> partidoUsuarios) {
        this.partidoUsuarios = partidoUsuarios;
    }




}


